// Occasional CRM cleanup / discovery driven by the NetHunt export. NOT part of the
// main ops cycle — run it for hygiene when you want. Compares R2 subscribers.csv against
// the NetHunt CRM export (which has email + LinkedIn + name) to surface:
//   - duplicate clusters inside the CRM (the same person across sources)
//   - CRM contacts already in / missing from NetHunt
//   - emailless CRM rows whose LinkedIn/name matches a NetHunt email (backfill)
// Writes a report to data/reports/crm/. With --write it backfills those emails into the
// CRM (safe enrichment only — it never deletes rows; dedup stays a manual review).
//   npm run crm:cleanup [-- --nethunt data/nethunt_contacts.csv --write]
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { parseCsv, norm, lower, stripBom, headerFinder } from './lib/csv.mjs';
import { r2ReadText, r2WriteText } from './lib/r2.mjs';
import { parseCrm, serializeCrm, mergeContacts, CRM_KEY, normLinkedin, splitName } from './lib/crm.mjs';
import { transliterate } from './lib/translit.mjs';

const argv = process.argv.slice(2);
const opts = { nethunt: 'data/nethunt_contacts.csv', write: false };
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === '--nethunt') opts.nethunt = argv[++i];
  else if (a === '--write') opts.write = true;
}
const OUT = 'data/reports/crm';
await mkdir(OUT, { recursive: true });

const nameKey = (first, last) => `${lower(transliterate(first))} ${lower(transliterate(last))}`.trim();
const display = (x) => (`${x.first || ''} ${x.last || ''}`.trim() || x.email || x.linkedin || '?');

// --- NetHunt export ---
const nhRows = parseCsv(stripBom(await readFile(opts.nethunt, 'utf8')));
if (nhRows.length < 2) { console.error(`No rows in ${opts.nethunt}.`); process.exit(1); }
const find = headerFinder(nhRows[0]);
const nc = {
  email: find(['email', 'e-mail']),
  first: find(['first name', 'first']),
  last: find(['last name', 'last']),
  name: find(['name', 'full name']),
  linkedin: find(['linkedin', 'linkedin url']),
};
const nethunt = [];
for (const r of nhRows.slice(1)) {
  const get = (i) => (i >= 0 ? norm(r[i]) : '');
  let first = get(nc.first), last = get(nc.last);
  if (!first && !last && get(nc.name)) ({ first, last } = splitName(get(nc.name)));
  nethunt.push({ email: lower(get(nc.email)), linkedin: normLinkedin(get(nc.linkedin)), first, last, nk: nameKey(first, last) });
}
const nhByEmail = new Map(), nhByLinkedin = new Map(), nhByName = new Map();
for (const c of nethunt) {
  if (c.email) nhByEmail.set(c.email, c);
  if (c.linkedin) nhByLinkedin.set(c.linkedin, c);
  if (c.nk) nhByName.set(c.nk, c);
}

// --- CRM ---
const rows = [...parseCrm(r2ReadText(CRM_KEY)).values()];
if (!rows.length) { console.error('CRM subscribers.csv is empty.'); process.exit(1); }

// internal duplicate clusters (same person key on >1 row, e.g. across sources)
const clusters = new Map();
for (const r of rows) {
  const k = r.email || r.linkedin || nameKey(r.first, r.last);
  if (!k) continue;
  if (!clusters.has(k)) clusters.set(k, []);
  clusters.get(k).push(r);
}
const dupes = [...clusters.values()].filter((v) => v.length > 1);

// coverage vs NetHunt + email backfill candidates
let inNh = 0;
const backfills = [];
for (const r of rows) {
  const m = (r.email && nhByEmail.get(r.email)) || (r.linkedin && nhByLinkedin.get(r.linkedin)) || nhByName.get(nameKey(r.first, r.last));
  if (m) inNh++;
  if (!r.email && m && m.email) backfills.push({ row: r, email: m.email });
}

// NetHunt contacts not matched in the community CRM (includes unrelated CRM rows)
const crmEmails = new Set(rows.map((r) => r.email).filter(Boolean));
const crmLinkedin = new Set(rows.map((r) => r.linkedin).filter(Boolean));
const crmNames = new Set(rows.map((r) => nameKey(r.first, r.last)).filter(Boolean));
const nethuntOnly = nethunt.filter((c) =>
  !((c.email && crmEmails.has(c.email)) || (c.linkedin && crmLinkedin.has(c.linkedin)) || (c.nk && crmNames.has(c.nk))));

// --- apply safe enrichment (email backfill) on --write ---
let written = 0;
if (opts.write && backfills.length) {
  for (const b of backfills) b.row.email = b.email;
  const fresh = new Map();
  mergeContacts(fresh, rows);
  r2WriteText(CRM_KEY, serializeCrm(fresh));
  written = backfills.length;
}

const md = `# CRM cleanup report (vs NetHunt)

_Generated by \`npm run crm:cleanup\`. NetHunt source: \`${opts.nethunt}\` (${nethunt.length} rows)._

- **CRM contacts:** ${rows.length}
- **Already in NetHunt:** ${inNh} · **not in NetHunt:** ${rows.length - inNh}
- **Duplicate clusters in CRM:** ${dupes.length} (review — never auto-merged)
- **Emailless rows backfillable from NetHunt:** ${backfills.length}${opts.write ? ` — written: ${written}` : ' — run with `--write` to apply'}
- **NetHunt rows not matched in the community CRM:** ${nethuntOnly.length}

## Duplicate clusters (same person across sources)

${dupes.slice(0, 80).map((v) => `- ${display(v[0])} — sources: ${[...new Set(v.map((x) => x.source))].join(', ')}`).join('\n') || '_none_'}
${dupes.length > 80 ? `\n…and ${dupes.length - 80} more.\n` : ''}
## Backfillable emails (LinkedIn/name → NetHunt email)

${backfills.slice(0, 100).map((b) => `- ${display(b.row)} (${b.row.source}) → ${b.email}`).join('\n') || '_none_'}
${backfills.length > 100 ? `\n…and ${backfills.length - 100} more.\n` : ''}`;
await writeFile(path.join(OUT, 'crm-cleanup.md'), md);

console.log(`CRM ${rows.length} · in NetHunt ${inNh} · dup clusters ${dupes.length} · backfillable ${backfills.length}${opts.write ? ` (wrote ${written})` : ''} · NetHunt-only ${nethuntOnly.length}`);
console.log(`Report -> ${OUT}/crm-cleanup.md`);
